"""Add token_id to MarketData

Revision ID: 1b790b060a83
Revises: fb220c517598
Create Date: 2025-03-05 11:01:03.858701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b790b060a83'
down_revision: Union[str, None] = 'fb220c517598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data', sa.Column('token_id', sa.String(), nullable=False))
    op.drop_column('market_data', 'token_address')
    op.drop_column('market_data', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('market_data', sa.Column('token_address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('market_data', 'token_id')
    # ### end Alembic commands ###
