"""Added timestamp column

Revision ID: 1ce0a31fd346
Revises: 1b790b060a83
Create Date: 2025-03-05 11:37:08.548105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce0a31fd346'
down_revision: Union[str, None] = '1b790b060a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data', 'timestamp')
    # ### end Alembic commands ###
